dist: trusty
language: php

php:
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

# This triggers builds to run on the new TravisCI infrastructure.
# See: https://docs.travis-ci.com/user/reference/trusty#Container-based-with-sudo%3A-false
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs -l --standard=psr2 . include
